<?php ob_start(); ?>
<h1><?= e($incident['title']) ?></h1>
<div class="card"><p><span class="badge <?= e($incident['severity']) ?>"><?= e(t($incident['severity'])) ?></span> <b><?= e(t('ID:')) ?></b> <code><?= e($incident['external_id']) ?></code> <b><?= e(t('Status:')) ?></b> <?= e($incident['status']) ?> <b><?= e(t('Confidence:')) ?></b> <?= e($incident['confidence'] ? t($incident['confidence']) : '') ?></p><?php if($incident['server_hostname']): ?><p><b><?= e(t('Server:')) ?></b> <?= e($incident['server_hostname']) ?></p><?php endif ?><p><?= e($incident['summary']) ?></p><?php if($timeline): ?><div class="details-grid"><?php foreach($timeline as $k=>$v): ?><div><b><?= e(str_replace('_',' ',$k)) ?>:</b> <?= e($v) ?></div><?php endforeach ?></div><?php endif ?><p class="muted"><?= e(t('Imported:')) ?> <?= e($incident['imported_at']) ?> <?= $incident['source_file'] ? '('.e($incident['source_file']).')' : '' ?></p></div>

<div class="card"><h2><?= e(t('Threat IPs')) ?> (<?= count($threatIps) ?>)</h2><?php if(!$threatIps): ?><p class="muted"><?= e(t('None recorded for this incident.')) ?></p><?php else: ?><table><tr><th>IP</th><th><?= e(t('Classification')) ?></th><th><?= e(t('Risk')) ?></th><th><?= e(t('Confidence')) ?></th><th><?= e(t('Hits')) ?></th><th><?= e(t('Recommended action')) ?></th><th><?= e(t('Notes')) ?></th></tr><?php foreach($threatIps as $ip): ?><tr><td><code><?= e($ip['ip']) ?></code></td><td><?= e(t($ip['classification'])) ?></td><td><span class="badge <?= e($ip['risk']) ?>"><?= e(t($ip['risk'])) ?></span></td><td><?= e($ip['confidence'] ? t($ip['confidence']) : '') ?></td><td><?= e($ip['hit_count']) ?></td><td><?= e($ip['recommended_action']) ?></td><td><?= e($ip['notes']) ?></td></tr><?php endforeach ?></table><p><a class="btn small" href="/threat-ips"><?= e(t('View all Threat IPs')) ?></a></p><?php endif ?></div>

<?php if($excludedIps): ?><div class="card"><h2><?= e(t('Do not block from this incident')) ?></h2><table><tr><th>IP</th><th><?= e(t('Classification')) ?></th><th><?= e(t('Reason')) ?></th></tr><?php foreach($excludedIps as $ip): ?><tr><td><code><?= e($ip['ip'] ?? '') ?></code></td><td><?= e($ip['classification'] ?? '') ?></td><td><?= e($ip['reason'] ?? '') ?></td></tr><?php endforeach ?></table></div><?php endif ?>

<div class="card"><h2><?= e(t('Signatures')) ?> (<?= count($signatures) ?>)</h2><?php if(!$signatures): ?><p class="muted"><?= e(t('None recorded for this incident.')) ?></p><?php else: ?><table><tr><th><?= e(t('Enabled')) ?></th><th><?= e(t('Name')) ?></th><th><?= e(t('Risk')) ?></th><th><?= e(t('Type')) ?></th><th><?= e(t('Pattern')) ?></th></tr><?php foreach($signatures as $s): ?><tr><td><?= $s['enabled']?e(t('yes')):e(t('no')) ?></td><td><a href="/signatures/<?= e($s['id']) ?>"><?= e($s['name']) ?></a></td><td><span class="badge <?= e($s['risk']) ?>"><?= e(t($s['risk'])) ?></span></td><td><?= e($s['type']) ?></td><td><?= e($s['pattern_type']) ?></td></tr><?php endforeach ?></table><?php endif ?></div>

<div class="card"><h2><?= e(t('File IOCs')) ?> (<?= count($fileIocs) ?>)</h2><?php if(!$fileIocs): ?><p class="muted"><?= e(t('None recorded for this incident.')) ?></p><?php else: foreach($fileIocs as $ioc): $names=json_decode((string)$ioc['names_json'],true)?:[]; $seen=$seenByHash[$ioc['sha256']]??[]; ?><div class="card" style="margin-bottom:8px"><p><span class="badge <?= e($ioc['risk'] ?? 'medium') ?>"><?= e($ioc['risk']?t($ioc['risk']):'') ?></span> <b><?= implode(', ', array_map('htmlspecialchars', $names)) ?></b> <span class="muted"><?= e($ioc['role']) ?><?= $ioc['scope']?' · '.e($ioc['scope']):'' ?></span></p><p><code><?= $ioc['sha256'] ? e($ioc['sha256']) : e(t('(hash not yet collected)')) ?></code></p><?php if($seen): ?><p class="muted"><b><?= e(t('Found on this server:')) ?></b></p><table><tr><th><?= e(t('User')) ?></th><th><?= e(t('Site')) ?></th><th><?= e(t('Path')) ?></th><th><?= e(t('Status')) ?></th><th><?= e(t('Last seen')) ?></th></tr><?php foreach($seen as $row): ?><tr><td><?= e($row['user_name'] ?? '') ?></td><td><?= e($row['site_name'] ?? '') ?></td><td><code><?= e($row['path']) ?></code></td><td><?= $row['is_missing']?e(t('deleted')):e(t('present')) ?></td><td><?= e($row['last_seen_at']) ?></td></tr><?php endforeach ?></table><?php else: ?><p class="muted"><?= e(t('Not found on this server (not scanned, already removed, or was never hashed).')) ?></p><?php endif ?></div><?php endforeach; endif ?></div>

<div class="card"><h2><?= e(t('Affected sites')) ?></h2><?php foreach(['confirmed_artifacts'=>t('Confirmed artifacts'),'related_confirmed_activity'=>t('Related confirmed activity'),'operator_ip_observed_in_access_logs_not_equal_to_confirmed_compromise'=>t('Operator IP seen in logs, compromise not confirmed')] as $key=>$label): if(empty($affectedAssets[$key])) continue; ?><h3><?= e($label) ?></h3><ul><?php foreach($affectedAssets[$key] as $name): $site=$siteByName[$name]??null; ?><li><a href="/findings?site=<?= urlencode($name) ?>"><?= e($name) ?></a><?= $site?' <span class="muted">('.e($site['user_name'] ?? '').')</span>':' <span class="muted">'.e(t('not in current inventory')).'</span>' ?></li><?php endforeach ?></ul><?php endforeach ?></div>

<?php if($pathIndicators): ?><div class="card"><h2><?= e(t('Path indicators')) ?></h2><table><tr><th><?= e(t('Pattern')) ?></th><th><?= e(t('Risk')) ?></th><th><?= e(t('Notes')) ?></th></tr><?php foreach($pathIndicators as $p): ?><tr><td><code><?= e($p['pattern'] ?? '') ?></code></td><td><?= e($p['risk']?t($p['risk']):'') ?></td><td><?= e($p['notes'] ?? '') ?></td></tr><?php endforeach ?></table></div><?php endif ?>

<?php if($responseActions): ?><div class="card"><h2><?= e(t('Response actions')) ?></h2><div class="details-grid"><?php foreach($responseActions as $k=>$v): ?><div><b><?= e(str_replace('_',' ',$k)) ?>:</b> <?= e(is_bool($v)?($v?'yes':'no'):$v) ?></div><?php endforeach ?></div></div><?php endif ?>
<?php $content=ob_get_clean(); include base_path('resources/views/layouts/app.php'); ?>
