<?php ob_start(); $scanCtx=$scanCtx??(function_exists('scan_active_context')?scan_active_context():[]); $scanDisabled=($scanCtx['running']??false)&&!($scanCtx['stale']??false); ?>
<h1><?= e(t('Dashboard')) ?></h1><p class="muted"><?= e(t('Jura AV Monitor is the built-in malware detection module of Jura Server Guard.')) ?></p>
<div class="card"><h2><?= e(t('Run scan')) ?></h2><div class="actions"><?php foreach(['fast'=>'Fast scan','standard'=>'Standard scan','deep'=>'Deep scan'] as $profile=>$label): ?><form method="post" action="/scan/start" class="inline-form"><input type="hidden" name="profile" value="<?= e($profile) ?>"><input type="hidden" name="scope" value="full"><select class="input" name="max_seconds"><option value="300"><?= e(t('5 min')) ?></option><option value="900"><?= e(t('15 min')) ?></option><option value="1800"><?= e(t('30 min')) ?></option><option value="0"><?= e(t('Unlimited/manual')) ?></option></select><button class="btn" <?= $scanDisabled?'disabled':'' ?>><?= e(t($label)) ?></button></form><?php endforeach ?></div><?php if($scanDisabled): ?><p class="muted"><b><?= e(t('Another scan is already running: Scan #:id.', ['id'=>$scanCtx['run']['id']??'pending'])) ?></b> <a href="/scan/active"><?= e(t('View active scan details')) ?></a>.</p><?php endif ?></div>
<div class="grid"><?php foreach ([['Last scan',$last['started_at']??'never'],['Profile',$last['profile']??'n/a'],['Users count',$users],['Sites count',$sites],['Files scanned',$last['files_scanned']??0],['New findings',$new],['Critical findings',$crit],['High findings',$high],['Quarantine count',$q]] as $c): ?><div class="card"><div class="muted"><?= e(t($c[0])) ?></div><h2><?= e(t((string)$c[1])) ?></h2></div><?php endforeach ?></div>

<div class="card"><h2><?= e(t('Scan history')) ?></h2><div class="table-scroll"><table><tr><th><?= e(t('ID')) ?></th><th><?= e(t('Profile')) ?></th><th><?= e(t('Scope')) ?></th><th><?= e(t('Status')) ?></th><th><?= e(t('Scanned files')) ?></th><th><?= e(t('Skipped media')) ?></th><th><?= e(t('Skipped dirs')) ?></th><th><?= e(t('Findings')) ?></th><th><?= e(t('Elapsed')) ?></th><th><?= e(t('Note')) ?></th><th data-no-sort><?= e(t('Report')) ?></th></tr><?php foreach($scanRuns ?? [] as $r): $elapsed=($r['finished_at']&&$r['started_at'])?(strtotime($r['finished_at'])-strtotime($r['started_at'])).'s':t('running'); $reportReady=in_array(($r['status']??''),['completed','completed_with_limit'],true); ?><tr><td><?= e($r['id']) ?></td><td><?= e(t($r['profile'] ?? 'fast')) ?></td><td><?= e(t($r['scope_type'])) ?> <?= e($r['scope_value'] ?? '') ?></td><td><?= e(t($r['status'])) ?></td><td><?= e($r['files_scanned']) ?></td><td><?= e($r['skipped_media'] ?? 0) ?></td><td><?= e($r['skipped_directories'] ?? 0) ?></td><td><?= e($r['findings_count']) ?></td><td><?= e($elapsed) ?></td><td><?= ($r['status']??'')==='completed_with_limit' ? '<span class="badge medium">'.e(t('Stopped by max seconds/files; scan may be incomplete')).'</span> ' : '' ?><?= e($r['error_text'] ?? '') ?></td><td><?php if($reportReady): ?><a class="btn small" href="/reports/scan?run_id=<?= e($r['id']) ?>"><?= e(t('Download report')) ?></a><?php else: ?><span class="muted">—</span><?php endif ?></td></tr><?php endforeach ?></table></div></div>

<div class="card"><h2><?= e(t('Recent suspicious log events')) ?></h2><div class="table-scroll"><table class="log-table dashboard-log-table"><tr><th><?= e(t('Risk')) ?></th><th><?= e(t('Date/Time')) ?></th><th><?= e(t('Site / Source log')) ?></th><th><?= e(t('IP')) ?></th><th><?= e(t('Method')) ?></th><th><?= e(t('URI')) ?></th><th data-no-sort><?= e(t('Raw / Actions')) ?></th></tr>
<?php $threatIps=$threatIps??[]; foreach($logs as $l): $id='log-'.$l['id']; $dt=$l['created_at'] ? str_replace('-', '/', $l['created_at']) : ''; $ti=$threatIps[$l['ip']]??null; $networkBlocked=$ti&&in_array(($ti['firewall_status']??''),['blocked','network_blocked'],true); $afterBlock=$networkBlocked&&!empty($ti['blocked_at'])&&strtotime((string)($l['created_at']??''))>strtotime((string)$ti['blocked_at']); ?>
<tr><td><span class="badge <?= e($l['risk']) ?>"><?= e(t($l['risk'])) ?></span></td><td class="nowrap"><?= e($dt) ?></td><td><b><?= e(log_event_site_label($l)) ?></b><br><span class="source-log" title="<?= e($l['log_path']??'') ?>"><?= e(basename($l['log_path']??'')) ?><?= isset($l['line_number'])?':'.e($l['line_number']):'' ?></span></td><td class="nowrap"><?= e($l['ip']) ?> <?php if($ti): ?><span class="badge <?= e($ti['risk']) ?>" title="<?= e(t($ti['classification'])) ?>"><?= e(t($ti['classification'])) ?></span> <a class="btn small" href="/threat-ips?ip=<?= urlencode($l['ip']) ?>&event_id=<?= e($l['id']) ?>"><?= e(t('Open IP')) ?></a><?php else: ?><a class="btn small" href="/threat-ips?ip=<?= urlencode($l['ip']) ?>&event_id=<?= e($l['id']) ?>"><?= e(t('Flag IP')) ?></a><?php endif ?></td><td><?= e($l['method']) ?></td><td class="uri-cell"><span title="<?= e($l['uri']) ?>"><?= e(mb_strimwidth($l['uri'] ?? '',0,110,'…')) ?></span><button class="btn small" onclick="copyText(<?= e(json_encode($l['uri'] ?? '')) ?>);return false"><?= e(t('Copy')) ?></button></td><td><?= e(mb_strimwidth($l['raw_line'],0,100,'…')) ?> <button class="btn small" onclick="toggleDetails('<?= e($id) ?>');return false"><?= e(t('Details')) ?></button></td></tr>
<tr id="<?= e($id) ?>" class="details-row" style="display:none"><td colspan="7"><div class="details-grid"><div><b><?= e(t('Risk:')) ?></b> <?= e(t($l['risk'])) ?></div><div><b><?= e(t('Timestamp:')) ?></b> <?= e($dt) ?></div><div><b><?= e(t('IP:')) ?></b> <?= e($l['ip']) ?><?php if($networkBlocked): ?> <span class="badge low"><?= e(t('Network rule active')) ?></span><?php if($afterBlock): ?> <span class="badge critical"><?= e(t('Request after block')) ?></span><?php endif ?><?php endif ?></div><div><b><?= e(t('Method:')) ?></b> <?= e($l['method']) ?></div><div><b><?= e(t('Host/Site:')) ?></b> <?= e(log_event_site_label($l)) ?></div><div><b><?= e(t('Source log:')) ?></b> <code><?= e($l['log_path'] ?? '') ?></code><?= isset($l['line_number']) ? ':'.e($l['line_number']) : '' ?></div><div class="wide"><b><?= e(t('URI:')) ?></b> <code><?= e($l['uri']) ?></code> <button class="btn small" onclick="copyText(<?= e(json_encode($l['uri'] ?? '')) ?>);return false"><?= e(t('Copy URI')) ?></button></div><div class="wide"><b><?= e(t('Matched reason:')) ?></b> <?= e($l['event_type'] ?? '') ?></div><div class="wide"><b><?= e(t('Raw log line:')) ?></b> <button class="btn small" onclick="copyText(<?= e(json_encode($l['raw_line'] ?? '')) ?>);return false"><?= e(t('Copy raw')) ?></button><pre><?= e($l['raw_line']) ?></pre></div><div class="wide actions"><b><?= e(t('Emergency actions')) ?>:</b> <a class="btn small" href="/logs?event_id=<?= e($l['id']) ?>#<?= e($id) ?>"><?= e(t('Open log event')) ?></a> <a class="btn small" href="/threat-ips?ip=<?= urlencode($l['ip']) ?>&event_id=<?= e($l['id']) ?>"><?= e(t($ti ? 'Open IP' : 'Flag IP')) ?></a><?php if(config('guard.firewall_actions_enabled')&&!$networkBlocked): ?> <form method="post" action="/threat-ips/block" class="inline-form" onsubmit="return submitIpBlock(this,<?= e(json_encode(t('Block this IP in the server firewall?'))) ?>)"><input type="hidden" name="ip" value="<?= e($l['ip']) ?>"><input type="hidden" name="log_event_id" value="<?= e($l['id']) ?>"><input type="hidden" name="classification" value="<?= e($ti['classification'] ?? 'scanner') ?>"><input type="hidden" name="risk" value="<?= e($ti['risk'] ?? $l['risk'] ?? 'high') ?>"><button class="btn danger small"><?= e(t('Block IP')) ?></button></form><?php endif ?><?php if(log_uri_looks_like_file($l['uri']??null)): ?> <a class="btn danger small" href="/logs/file?event_id=<?= e($l['id']) ?>"><?= e(t('Inspect requested file')) ?></a><?php endif ?></div></div></td></tr>
<?php endforeach ?></table></div></div>
<script>
function toggleDetails(id){
  const el=document.getElementById(id),opening=el.style.display==='none';
  el.style.display=opening?'table-row':'none';
  if(opening) history.replaceState(null,'','#'+id); else if(location.hash==='#'+id) history.replaceState(null,'',location.pathname+location.search);
}
function copyText(t){navigator.clipboard?navigator.clipboard.writeText(t):prompt('Copy',t)}
(function(){if(location.hash){var el=document.getElementById(location.hash.slice(1));if(el&&el.classList.contains('details-row'))el.style.display='table-row';}})();
</script>
<?php $content=ob_get_clean(); include base_path('resources/views/layouts/app.php'); ?>
