<?php ob_start();
$activeLock = $activeLock ?? null;
$active = $activeScan ?? null;
if (!$active && !empty($activeLock)) $active = ['id'=>'n/a','profile'=>'n/a','scope_type'=>'locked','scope_value'=>$activeLock['command'] ?? null,'started_at'=>$activeLock['started_at'] ?? null,'pid'=>$activeLock['pid'] ?? null,'status'=>'locked','files_scanned'=>0,'skipped_media'=>0,'skipped_directories'=>0,'findings_count'=>0];
$started = $active['started_at'] ?? $activeLock['started_at'] ?? null;
$pid = $active['pid'] ?? $activeLock['pid'] ?? null;
$total = $active['total_files_estimated'] ?? null;
$scanned = (int)($active['files_scanned'] ?? 0);
$progress = $total ? min(100, round(($scanned / max(1, (int)$total)) * 100, 1)) : null;
$elapsed = $started ? format_duration(max(0, time() - strtotime($started))) : 'n/a';
$heartbeatAge = !empty($active['last_heartbeat_at']) ? max(0, time() - strtotime($active['last_heartbeat_at'])) : null;
$isStale = scan_is_stale($active);
?>
<?php if(!empty($active) || !empty($activeLock)): ?><meta http-equiv="refresh" content="5"><?php endif ?>
<h1><?= !empty($activeOnly) ? 'Active scan' : 'Dashboard' ?></h1><p class="muted">Jura AV Monitor is the built-in malware detection module of Jura Server Guard.</p>
<?php if(!empty($active) || !empty($activeLock)): ?>
<div class="card active-scan"><h2>Scan is running</h2><div class="details-grid">
<div><b>Scan run ID:</b> <?= e($active['id']) ?></div><div><b>Profile:</b> <?= e($active['profile'] ?? 'fast') ?></div><div><b>Scope:</b> <?= e($active['scope_type']) ?></div><div><b>Target:</b> <?= e($active['scope_value'] ?? 'full server') ?></div><div><b>Started at:</b> <?= e($started) ?></div><div><b>PID:</b> <?= e($pid) ?></div><div><b>Files scanned:</b> <?= e($scanned) ?></div><div><b>Estimated total files:</b> <?= e($total ?? 'estimating') ?></div><div><b>Progress:</b> <?= e($progress !== null ? $progress.'%' : 'estimating') ?></div><div><b>Skipped media:</b> <?= e($active['skipped_media'] ?? 0) ?></div><div><b>Skipped directories:</b> <?= e($active['skipped_directories'] ?? 0) ?></div><div><b>Findings:</b> <?= e($active['findings_count'] ?? 0) ?></div><div><b>Elapsed time:</b> <?= e($elapsed) ?></div><div><b>Last heartbeat:</b> <?= e($heartbeatAge !== null ? $heartbeatAge.' seconds ago' : 'n/a') ?></div><div><b>Status:</b> <?= e($active['status'] ?? 'running') ?></div><div><b>Current site:</b> <?= e($active['current_site'] ?? '') ?></div><div class="wide"><b>Current path:</b> <code><?= e($active['current_path'] ?? '') ?></code></div><div class="wide"><b>Progress message:</b> <?= e($active['progress_message'] ?? '') ?></div><?php if(!empty($active['error_text'])): ?><div class="wide"><b>Error:</b> <?= e($active['error_text']) ?></div><?php endif ?><?php if($activeLock): ?><div class="wide"><b>Lock:</b> <?= e($activeLock['command'] ?? '') ?> since <?= e($activeLock['started_at'] ?? '') ?> PID <?= e($activeLock['pid'] ?? '') ?></div><?php endif ?>
</div><div class="actions"><a class="btn" href="/scan/active">Refresh</a><form method="post" action="/scan/stop"><button class="btn danger">Stop scan</button></form><?php if($isStale): ?><form method="post" action="/scan/force-unlock"><button class="btn danger">Force unlock stale scan</button></form><?php endif ?></div></div>
<?php endif ?>
<?php if(empty($activeOnly)): ?>
<div class="card"><h2>Run scan</h2><?php if(!empty($active) || !empty($activeLock)): ?><p class="muted">Start is disabled because <?= e($activeLock['command'] ?? 'another scan') ?> is already running since <?= e($started) ?> PID <?= e($pid) ?>.</p><?php endif ?><div class="actions"><?php foreach(['fast'=>'Fast scan','standard'=>'Standard scan','deep'=>'Deep scan'] as $profile=>$label): ?><form method="post" action="/scan/start" style="display:inline"><input type="hidden" name="profile" value="<?= e($profile) ?>"><input type="hidden" name="scope" value="full"><button class="btn" <?= (!empty($active) || !empty($activeLock)) ? 'disabled title="A scan is already running"' : '' ?>><?= e($label) ?></button></form><?php endforeach ?></div></div>
<div class="grid"><?php foreach ([['Last scan',$last['started_at']??'never'],['Profile',$last['profile']??'n/a'],['Users count',$users],['Sites count',$sites],['Files scanned',$last['files_scanned']??0],['New findings',$new],['Critical findings',$crit],['High findings',$high],['Quarantine count',$q]] as $c): ?><div class="card"><div class="muted"><?= e($c[0]) ?></div><h2><?= e($c[1]) ?></h2></div><?php endforeach ?></div>
<?php endif ?>
<div class="card"><h2>Scan history</h2><table><tr><th>ID</th><th>Profile</th><th>Scope</th><th>Status</th><th>Scanned files</th><th>Total</th><th>Skipped media</th><th>Skipped dirs</th><th>Findings</th><th>Elapsed</th></tr><?php foreach($scanRuns ?? [] as $r): $elapsed=($r['started_at'])?format_duration(max(0, strtotime($r['finished_at'] ?: now())-strtotime($r['started_at']))):'n/a'; ?><tr><td><a href="/scan/active"><?= e($r['id']) ?></a></td><td><?= e($r['profile'] ?? 'fast') ?></td><td><?= e($r['scope_type']) ?> <?= e($r['scope_value'] ?? '') ?></td><td><?= e($r['status']) ?></td><td><?= e($r['files_scanned']) ?></td><td><?= e($r['total_files_estimated'] ?? '') ?></td><td><?= e($r['skipped_media'] ?? 0) ?></td><td><?= e($r['skipped_directories'] ?? 0) ?></td><td><?= e($r['findings_count']) ?></td><td><?= e($elapsed) ?></td></tr><?php endforeach ?></table></div>
<?php if(empty($activeOnly)): ?>
<div class="card"><h2>Recent suspicious log events</h2><table class="log-table"><tr><th>Risk</th><th>Date/Time</th><th>IP</th><th>Method</th><th>URI</th><th>Raw / Actions</th></tr><?php foreach($logs as $l): $id='log-'.$l['id']; $dt=$l['created_at'] ? str_replace('-', '/', $l['created_at']) : ''; ?><tr><td><span class="badge <?= e($l['risk']) ?>"><?= e($l['risk']) ?></span></td><td class="nowrap"><?= e($dt) ?></td><td class="nowrap"><?= e($l['ip']) ?></td><td><?= e($l['method']) ?></td><td class="uri-cell"><span title="<?= e($l['uri']) ?>"><?= e(mb_strimwidth($l['uri'] ?? '',0,90,'…')) ?></span><button class="btn small" onclick="copyText(<?= json_encode($l['uri'] ?? '') ?>);return false">Copy</button></td><td><?= e(mb_strimwidth($l['raw_line'],0,100,'…')) ?> <button class="btn small" onclick="toggleDetails('<?= e($id) ?>');return false">Details</button></td></tr><tr id="<?= e($id) ?>" class="details-row" style="display:none"><td colspan="6"><div class="details-grid"><div><b>Risk:</b> <?= e($l['risk']) ?></div><div><b>Timestamp:</b> <?= e($dt) ?></div><div><b>IP:</b> <?= e($l['ip']) ?></div><div><b>Method:</b> <?= e($l['method']) ?></div><div><b>Host/Site:</b> <?= e($l['site_name'] ?? '') ?></div><div><b>Source log:</b> <?= e($l['log_path'] ?? '') ?><?= isset($l['line_number']) ? ':'.e($l['line_number']) : '' ?></div><div class="wide"><b>URI:</b> <code><?= e($l['uri']) ?></code> <button class="btn small" onclick="copyText(<?= json_encode($l['uri'] ?? '') ?>);return false">Copy URI</button></div><div class="wide"><b>Matched reason:</b> <?= e($l['event_type'] ?? '') ?></div><div class="wide"><b>Raw log line:</b> <button class="btn small" onclick="copyText(<?= json_encode($l['raw_line'] ?? '') ?>);return false">Copy raw</button><pre><?= e($l['raw_line']) ?></pre></div></div></td></tr><?php endforeach ?></table></div>
<script>function toggleDetails(id){const el=document.getElementById(id);el.style.display=el.style.display==='none'?'table-row':'none'}function copyText(t){navigator.clipboard?navigator.clipboard.writeText(t):prompt('Copy',t)}</script>
<?php endif ?>
<?php $content=ob_get_clean(); include base_path('resources/views/layouts/app.php'); ?>
