<?php ob_start(); ?><h1><?= e(t('Search')) ?></h1><p class="muted"><?= e(t('Search across scanned files, findings, quarantine, logs, signatures, and incidents by filename/path, exact SHA-256, or IP address.')) ?></p>
<form action="/search" style="margin-bottom:16px"><input class="input" style="width:60%" name="q" placeholder="<?= e(t('filename, path, sha256, or IP')) ?>" value="<?= e($q) ?>" autofocus> <button class="btn"><?= e(t('Search')) ?></button></form>
<?php if($q === ''): ?><p class="muted"><?= e(t('Enter a search term above.')) ?></p><?php else: ?>
<?php if(isset($file_snapshots)): ?><div class="card"><h2><?= e(t('Scanned files')) ?> (<?= count($file_snapshots) ?>)</h2><?php if(!$file_snapshots): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php else: ?><table><tr><th><?= e(t('User')) ?></th><th><?= e(t('Site')) ?></th><th><?= e(t('Path')) ?></th><th><?= e(t('Status')) ?></th><th>SHA256</th><th><?= e(t('Last seen')) ?></th></tr><?php foreach($file_snapshots as $fs): ?><tr><td><?= e($fs['user_name'] ?? '') ?></td><td><?= e($fs['site_name'] ?? '') ?></td><td><code><?= e($fs['path']) ?></code></td><td><?= $fs['is_missing']?e(t('deleted')):e(t('present')) ?></td><td><?php if($fs['sha256']): ?><a href="/search?q=<?= e($fs['sha256']) ?>"><code><?= e(mb_strimwidth($fs['sha256'],0,16,'…')) ?></code></a><?php endif ?></td><td><?= e($fs['last_seen_at']) ?></td></tr><?php endforeach ?></table><?php endif ?></div><?php endif ?>
<?php if(isset($findings)): ?><div class="card"><h2><?= e(t('Findings')) ?> (<?= count($findings) ?>)</h2><?php if(!$findings): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php else: ?><table><tr><th><?= e(t('Risk')) ?></th><th><?= e(t('Type')) ?></th><th><?= e(t('User')) ?></th><th><?= e(t('Site')) ?></th><th><?= e(t('Path')) ?></th><th><?= e(t('Status')) ?></th></tr><?php foreach($findings as $f): ?><tr><td><span class="badge <?= e($f['risk']) ?>"><?= e(t($f['risk'])) ?></span></td><td><?= e($f['type']) ?></td><td><?= e($f['user_name'] ?? '') ?></td><td><?= e($f['site_name'] ?? '') ?></td><td><a href="/findings/<?= e($f['id']) ?>"><code><?= e($f['path']) ?></code></a></td><td><?= e(t($f['status'])) ?></td></tr><?php endforeach ?></table><?php endif ?></div><?php endif ?>
<?php if(isset($signatures)): ?><div class="card"><h2><?= e(t('Signatures')) ?> (<?= count($signatures) ?>)</h2><?php if(!$signatures): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php else: ?><table><tr><th><?= e(t('Name')) ?></th><th><?= e(t('Risk')) ?></th><th><?= e(t('Type')) ?></th><th><?= e(t('Pattern')) ?></th><th><?= e(t('Enabled')) ?></th></tr><?php foreach($signatures as $s): ?><tr><td><a href="/signatures/<?= e($s['id']) ?>"><?= e($s['name']) ?></a></td><td><span class="badge <?= e($s['risk']) ?>"><?= e(t($s['risk'])) ?></span></td><td><?= e($s['type']) ?></td><td><?= e($s['pattern_type']) ?></td><td><?= $s['enabled']?e(t('yes')):e(t('no')) ?></td></tr><?php endforeach ?></table><?php endif ?></div><?php endif ?>
<?php if(isset($file_iocs)): ?><div class="card"><h2><?= e(t('Incident file IOCs')) ?> (<?= count($file_iocs) ?>)</h2><?php if(!$file_iocs): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php else: foreach($file_iocs as $ioc): $names=json_decode((string)$ioc['names_json'],true)?:[]; ?><p><b><?= implode(', ', array_map('htmlspecialchars', $names)) ?></b> <span class="badge <?= e($ioc['risk'] ?? 'medium') ?>"><?= e($ioc['risk']?t($ioc['risk']):'') ?></span> <span class="muted"><?= e($ioc['role']) ?></span><br><?php if($ioc['sha256']): ?><code><a href="/search?q=<?= e($ioc['sha256']) ?>"><?= e($ioc['sha256']) ?></a></code><?php else: ?><span class="muted"><?= e(t('(hash not yet collected)')) ?></span><?php endif ?><?php if(!empty($ioc['incident_titles'])): ?> — <span class="muted"><?= e($ioc['incident_titles']) ?></span><?php endif ?></p><?php endforeach; endif ?></div><?php endif ?>
<?php if(isset($incidents)): ?><div class="card"><h2><?= e(t('Incidents')) ?> (<?= count($incidents) ?>)</h2><?php if(!$incidents): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php else: ?><table><tr><th><?= e(t('Severity')) ?></th><th><?= e(t('Title')) ?></th><th><?= e(t('Status')) ?></th></tr><?php foreach($incidents as $i): ?><tr><td><span class="badge <?= e($i['severity']) ?>"><?= e(t($i['severity'])) ?></span></td><td><a href="/incidents/<?= e($i['id']) ?>"><?= e($i['title']) ?></a></td><td><?= e($i['status']) ?></td></tr><?php endforeach ?></table><?php endif ?></div><?php endif ?>
<?php if(isset($quarantine)): ?><div class="card"><h2><?= e(t('Quarantine')) ?> (<?= count($quarantine) ?>)</h2><?php if(!$quarantine): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php else: ?><table><tr><th><?= e(t('Original path')) ?></th><th><?= e(t('Status')) ?></th><th><?= e(t('Date')) ?></th></tr><?php foreach($quarantine as $qi): ?><tr><td><code><?= e($qi['original_path']) ?></code></td><td><?= e(t($qi['status'])) ?></td><td><?= e($qi['created_at']) ?></td></tr><?php endforeach ?></table><?php endif ?></div><?php endif ?>
<?php if(isset($logs)): ?><div class="card"><h2><?= e(t('Suspicious logs')) ?> (<?= count($logs) ?>)</h2><?php if(!$logs): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php else: ?><table><tr><th><?= e(t('Risk')) ?></th><th><?= e(t('Site')) ?></th><th>IP</th><th><?= e(t('URI')) ?></th></tr><?php foreach($logs as $l): ?><tr><td><span class="badge <?= e($l['risk']) ?>"><?= e(t($l['risk'])) ?></span></td><td><?= e($l['site_name'] ?? '') ?></td><td><?= e($l['ip']) ?></td><td class="uri-cell"><?= e(mb_strimwidth($l['uri']??'',0,120,'…')) ?></td></tr><?php endforeach ?></table><?php endif ?></div><?php endif ?>
<?php if(isset($threat_ips)): ?><div class="card"><h2><?= e(t('Threat IPs')) ?> (<?= count($threat_ips) ?>)</h2><?php foreach($threat_ips as $ip): ?><p><code><?= e($ip['ip']) ?></code> <span class="badge <?= e($ip['risk']) ?>"><?= e(t($ip['risk'])) ?></span> <?= e(t($ip['classification'])) ?> — <?= e($ip['notes']) ?></p><?php endforeach; if(!$threat_ips): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php endif ?></div><?php endif ?>
<?php if(isset($trusted_ips)): ?><div class="card"><h2><?= e(t('Trusted IPs')) ?> (<?= count($trusted_ips) ?>)</h2><?php foreach($trusted_ips as $ip): ?><p><code><?= e($ip['ip']) ?></code> <?= e($ip['label']) ?></p><?php endforeach; if(!$trusted_ips): ?><p class="muted"><?= e(t('No matches.')) ?></p><?php endif ?></div><?php endif ?>
<?php endif ?>
<?php $content=ob_get_clean(); include base_path('resources/views/layouts/app.php'); ?>
