<?php
return [
    'default_locale' => env_value('JURA_DEFAULT_LOCALE', 'ru'),
    'scan_roots' => array_values(array_filter(array_map('trim', explode(',', (string) env_value('JURA_SCAN_ROOTS', '/var/www'))))),
    'site_pattern' => env_value('JURA_SITE_PATTERN', '/var/www/*/data/www/*'),
    'log_paths' => [
        '/var/www/*/data/logs/*.access.log',
        '/var/www/*/data/logs/*.error.log',
        '/var/www/httpd-logs/*.access.log',
        '/var/www/httpd-logs/*.error.log',
        '/var/log/secure',
        '/var/log/auth.log',
    ],
    'exclude_paths' => [
        '*/OLD/*', '*/old.*/*', '*/DUBL*/*', '*/dubl*/*', '*/*backup*/*',
        '*/__MACOSX/*', '*/node_modules/*', '*/vendor/*', '*/storage/logs/*',
        '*/cache/*', '*/tmp/*', '*/temp/*',
    ],
    'exclude_site_names' => ['OLD', 'DUBL', 'DUBL*', 'OLD_*', '*_backup_*', '*backup*', '__MACOSX'],
    'scan_old_dubl_by_default' => bool_env('JURA_SCAN_OLD_DUBL_BY_DEFAULT', false),
    'scan_storage_by_default' => bool_env('JURA_SCAN_STORAGE_BY_DEFAULT', false),
    'max_files_per_site' => (int) env_value('JURA_MAX_FILES_PER_SITE', 200000),
    'max_scan_seconds_per_site' => (int) env_value('JURA_MAX_SCAN_SECONDS_PER_SITE', 300),
    'max_file_size_for_hash_mb' => (int) env_value('JURA_MAX_FILE_SIZE_FOR_HASH_MB', 50),
    'hash_all_files' => bool_env('JURA_HASH_ALL_FILES', false),
    'hash_php_files' => bool_env('JURA_HASH_PHP_FILES', true),
    'hash_critical_files' => bool_env('JURA_HASH_CRITICAL_FILES', true),
    'quarantine_path' => env_value('JURA_QUARANTINE_PATH', '/root/jura-server-guard/quarantine'),
    'web_actions_enabled' => bool_env('JURA_WEB_ACTIONS_ENABLED', false),
    'scan_profile' => env_value('JURA_SCAN_PROFILE', 'fast'),
    'timer_scan_profile' => env_value('JURA_TIMER_SCAN_PROFILE', 'fast'),
    'scan_interval_minutes' => (int) env_value('JURA_SCAN_INTERVAL_MINUTES', 30),
    'max_file_read_bytes' => (int) env_value('JURA_MAX_FILE_READ_BYTES', 262144),
    'ai_signatures_enabled' => bool_env('JURA_AI_SIGNATURES_ENABLED', false),
    'ai_provider' => env_value('JURA_AI_PROVIDER', 'openai'),
    'ai_model' => env_value('JURA_AI_MODEL', ''),
    'openai_enabled' => bool_env('JURA_OPENAI_ENABLED', false),
    'openai_api_key' => env_value('JURA_OPENAI_API_KEY', ''),
    'anthropic_enabled' => bool_env('JURA_ANTHROPIC_ENABLED', false),
    'anthropic_api_key' => env_value('JURA_ANTHROPIC_API_KEY', ''),
    'ai_chat_enabled' => bool_env('JURA_AI_CHAT_ENABLED', false),
    'auto_quarantine_obvious_shells' => bool_env('JURA_AUTO_QUARANTINE_OBVIOUS_SHELLS', false),
    'backup_integration_enabled' => bool_env('JURA_BACKUP_INTEGRATION_ENABLED', false),
    'backup_provider' => env_value('JURA_BACKUP_PROVIDER', 'disabled'),
    'ispmanager_detected' => bool_env('JURA_ISPMANAGER_DETECTED', false),
    'backup_root' => env_value('JURA_BACKUP_ROOT', '/var/backup'),
    'backup_browser_enabled' => bool_env('JURA_BACKUP_BROWSER_ENABLED', true),
    'backup_restore_enabled' => bool_env('JURA_BACKUP_RESTORE_ENABLED', false),
    'restore_current_file_to_quarantine' => bool_env('JURA_RESTORE_CURRENT_FILE_TO_QUARANTINE', true),
    'telegram_enabled' => bool_env('JURA_TELEGRAM_ENABLED', false),
    'telegram_bot_token' => env_value('JURA_TELEGRAM_BOT_TOKEN', ''),
    'telegram_chat_id' => env_value('JURA_TELEGRAM_CHAT_ID', ''),
    'notify_new_critical_high_findings' => bool_env('JURA_NOTIFY_NEW_CRITICAL_HIGH_FINDINGS', true),
    'notify_untrusted_webroot_files' => bool_env('JURA_NOTIFY_UNTRUSTED_WEBROOT_FILES', true),
    'notify_cron_changes' => bool_env('JURA_NOTIFY_CRON_CHANGES', true),
    'cron_monitor_enabled' => bool_env('JURA_CRON_MONITOR_ENABLED', true),
    'auto_signature_on_critical_findings' => bool_env('JURA_AUTO_SIGNATURE_ON_CRITICAL_FINDINGS', true),
];
