<?php
return [
 'malware_strings' => [
  ['name'=>'blackhat.pw callback','risk'=>'critical','type'=>'webshell','pattern'=>'blackhat.pw'], ['name'=>'bypass.pw callback','risk'=>'critical','type'=>'webshell','pattern'=>'bypass.pw'], ['name'=>'paste.mangsud.org loader','risk'=>'critical','type'=>'webshell','pattern'=>'paste.mangsud.org'],
  ['name'=>'MarketplaceVerificationBot','risk'=>'high','type'=>'webshell','pattern'=>'MarketplaceVerificationBot'], ['name'=>'BlackHat checker','risk'=>'critical','type'=>'webshell','pattern'=>'_bh_chk'], ['name'=>'BlackHat lock','risk'=>'critical','type'=>'webshell','pattern'=>'bh_vlock'], ['name'=>'bhvt marker','risk'=>'high','type'=>'webshell','pattern'=>'bhvt_'],
  ['name'=>'VerificationScript','risk'=>'high','type'=>'webshell','pattern'=>'VerificationScript/3.0'], ['name'=>'Domain Verification Script','risk'=>'high','type'=>'webshell','pattern'=>'Domain Verification Script'], ['name'=>'ALFA_DATA','risk'=>'critical','type'=>'webshell','pattern'=>'ALFA_DATA'], ['name'=>'alfacgiapi','risk'=>'critical','type'=>'webshell','pattern'=>'alfacgiapi'],
  ['name'=>'Leviathan Defender','risk'=>'critical','type'=>'webshell','pattern'=>'Leviathan Defender'], ['name'=>'SEBARIN','risk'=>'high','type'=>'webshell','pattern'=>'SEBARIN'], ['name'=>'target_folder marker','risk'=>'high','type'=>'webshell','pattern'=>'target_folder'], ['name'=>'deploy query','risk'=>'high','type'=>'webshell','pattern'=>'deploy=true'], ['name'=>'fileloc query','risk'=>'high','type'=>'webshell','pattern'=>'fileloc='], ['name'=>'delivery query','risk'=>'high','type'=>'webshell','pattern'=>'?delivery'],
 ],
 'php_functions' => ['eval($_','assert($_','system($_','passthru($_','shell_exec($_','proc_open($_','popen($_','base64_decode(','gzinflate(','str_rot13('],
 'suspicious_paths' => ['*/wp-content/uploads/*.php','*/uploads/*.php','*/upload/*.php','*/image/*.php','*/images/*.php','*/cache/*.php','*/tmp/*.php','*/temp/*.php','*/ALFA_DATA/alfacgiapi/*.php','*/wp-admin/js/widgets/.tmb/*.php'],
 'suspicious_names' => ['AuthControlIer.php','access.policy.php','session.manage.php','field.api.php','whewr.php','only.php','man.php','sponge.php','zebra.php','cunliaw.php','spoon.php','mah.php','home.php','gallery888.php'],
 'critical_changes' => ['wp-includes/plugin.php','index.php','.htaccess','.user.ini'],
 'important_changes' => ['wp-config.php','wp-admin/*','wp-includes/*','wp-content/plugins/*','configuration.php','config.php','admin/config.php'],
 'allowlist' => ['*/system/library/simple/php/simple_*.php','*/system/library/simple/php/filterit_*.php','*/admin/controller/extension/shipping/novaposhta.php','*/admin/controller/extension/module/technics/demo/*','*/system/storage/vendor/twig/twig/src/Environment.php','*/system/library/template/Twig/Environment.php','*/vendor/twig/twig/src/Environment.php','*/libraries/loader.php','*/libraries/cms/class/loader.php','*/administrator/components/com_jce/includes/loader.php','*/system/engine/loader.php','*/modification/system/engine/loader.php','*/storage*/modification/system/engine/loader.php','*/wp-content/plugins/*/index.php','*/wp-content/plugins/*/assets/*/index.php','*/wp-includes/blocks/*/view.asset.php','*/wp-includes/blocks/*/view.min.asset.php'],
];
